/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Applicant = t.iface([], {
  "id": "number",
  "firstname": "string",
  "lastname": "string",
  "email": "string",
  "created_on": "string",
  "info": "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  Applicant,
};
export default exportedTypeSuite;
